call plug#begin()
  Plug 'arcticicestudio/nord-vim'
call plug#end()
set autoindent
set expandtab
" indent on
set shiftround
set shiftwidth=4
set smarttab
set tabstop=4
set hlsearch
set ignorecase
set incsearch
set smartcase
set complete-=i
set lazyredraw
set display+=lastline
set encoding=utf-8
set linebreak
set scrolloff=1
set sidescrolloff=5
syntax enable
set wrap
set laststatus=2
set ruler
set wildmenu
set tabpagemax=50
colorscheme nord 
set cursorline
set number
set relativenumber
set noerrorbells
set visualbell
set mouse=a
set title
set background=dark
set foldmethod=indent
set foldnestmax=3
set nofoldenable
set autoread
set backspace=indent,eol,start
set backupdir=~/.vim/backup
set confirm
set dir=~/.cache/vim
set formatoptions+=j
set hidden
set history=1000
set nomodeline
set noswapfile
set nrformats-=octal
" set shell
set spell
set wildignore+=.pyc,.swp
