[drive]
type = drive
client_id = 266423233825-br94dcbsi2cmfpjg1j2790fir3pagm2n.apps.googleusercontent.com
client_secret = A54Z18Ezm5bxRkZXpuHQWgRS
scope = drive
token = {"access_token":"ya29.a0AfH6SMClxMUBLlebknxY36eDaKLgC2duyT-45Z0ixpcDOta-kr-0fep1MtSzzpTB_nfdM550O0kRSt0sH7jehKrrTb6my8oCCxN1uub265haUJaaSbQDSLijZ3-sjDiXB_4JCGD7xayNHgkOf3dmK6BeD1-EW4YAUt03","token_type":"Bearer","refresh_token":"1//0e-prnje7LvXHCgYIARAAGA4SNwF-L9IrzSP5s-Dn8WiHFqpvFNsy0OTVTUkkac_7jBf1kg0qL6XbPMnDWiYvjH-z9Lr7Ugxk4tQ","expiry":"2020-10-10T21:52:41.890405966+07:00"}

[dropbox]
type = dropbox
token = {"access_token":"8NbwiFl9vaMAAAAAAAAAAXgZuzAKMyAXlk94T1h30i-5GE4N2q0GYYs1YQjH0ixi","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}

