#!/usr/bin/env bash

# xrandr | grep 'connected'
xrandr --output DVI-I-1 --off
# xrandr --newmode "2560x1440_60.00"  312.25  2560 2752 3024 3488  1440 1443 1448 1493 -hsync +vsync
# xrandr --addmode HDMI-1 "2560x1440_60.00"
# xrandr --output HDMI-1 --primary --mode 2560x1440_60.00
# xrandr --output DVI-I-1 --mode 1600x900 --left-of HDMI-1 &
# xautolock -time 5 -locker "lock" &
# redshift-gtk &
# changedynamictheme colony &
# changetheme &
# wal -R -q &
# nextcloud &
# syncthing -no-browser &
feh --randomize --bg-fill "/mnt/data/_data/wallpaper/" --bg-fill "/mnt/data/_data/wallpaper/" &
dropbox &
numlockx on &
picom --experimental-backends &
exec /usr/bin/lxpolkit &
ibus-daemon -drx --panel /usr/lib/ibus/ibus-ui-gtk3 &
xfce4-clipman &
nm-applet &
udiskie -t &