#!/usr/bin/env bash

# nextcloud &
# syncthing -no-browser &
# xrandr --output DisplayPort-1 --primary --mode 2560x1080 &
# xrandr --output HDMI-0 --mode 1920x1080 --right-of DisplayPort-1 &
# xautolock -time 5 -locker "lock" &
# redshift-gtk &
# changedynamictheme colony &
# changetheme &
# wal -R -q &
feh --randomize --bg-fill "/home/huka/Dropbox/_data/wallpaper/"
dropbox &
numlockx on &
picom --experimental-backends &
exec /usr/bin/lxpolkit &
ibus-daemon -drx --panel /usr/lib/ibus/ibus-ui-gtk3 &
xfce4-clipman &
nm-applet &
udiskie -t &