#!/bin/bash

dir="${HOME}"'/wallpaper/'

change_wall() {
  DISPLAY=:0 wal -i "$dir" -n ; feh --no-fehbg --bg-fill "$(< "${HOME}/.cache/wal/wal")"
  dunstcolor
  roficolor
  qtile cmd-obj -o cmd -f restart
}

change_wall &