# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
# [character]                         # The name of the module we are configuring is "character"
# success_symbol = "[➜](bold green)"  # The "success_symbol" is set to "➜" with color "bold green"

# Use custom format
# format = """
# [┌───────────────────>](bold green)
# [│](bold green)$directory$rust$package
# [└─>](bold green) """

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
fish_style_pwd_dir_length = 3
read_only = " "
# truncation_symbol = "…/"

[battery]
disabled = true
# full_symbol = ""
# charging_symbol = ""
# discharging_symbol = ""

[character]
success_symbol = "[\\$>](bold green)"
error_symbol = "[\\$>](bold red)"
vicmd_symbol = "[\\$<](bold blue)"

[aws]
symbol = " "


[conda]
symbol = " "

[dart]
symbol = " "

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "