#!/bin/sh
bspc rule -r "*"

###---Autostart---###
nm-applet &
#xrdb ~/.Xresources &
picom -b --experimental-backends &
#nitrogen --restore &
dwall -s tokyo &
flameshot &
#killall "launchlemon"
#launchlemon &
launchpolybar &
#killall bspswallow
#pidof bspswallow | bspswallow &
ibus-daemon -drx --panel /usr/lib/ibus/ibus-ui-gtk3
nm-applet &
udiskie -t &

###---MONITORS---###
bspc monitor HDMI1 -d 1 2 3 4 5 6 7

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10

###---Rules---###
bspc rule -a mpv state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a guvcview state=floating rectangle=480x270+1440+810 sticky=on layer=above