#! /bin/sh

sxhkd &
$HOME/_bin/autostart
~/.config/polybar/launch.sh &
# Java App
wmname LG3D

# Change from ugly 'X' cursor when hovering over background
# xsetroot -cursor_name left_ptr

#Single monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#Dual monitor
#find out names with arandr or xrandr
# bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10

#BSPWM configuration
bspc config border_radius        10
bspc config border_width         0
bspc config window_gap           0
bspc config top_padding          0
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
# bspc config focus_follows_pointer true
bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

#Fullscreen applications
bspc rule -a inkscape state=fullscreen
bspc rule -a Spotify state=fullscreen
bspc rule -a Vlc state=fullscreen
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen
bspc rule -a Gimp state=fullscreen

#Floating applications
bspc rule -a Arandr state=floating
bspc rule -a feh state=floating
bspc rule -a Oblogout state=floating
bspc rule -a Xfce4-terminal state=floating

#Tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled

#open applications on specific workspaces
bspc rule -a doublecmd desktop='^1' follow=on
bspc rule -a Firefox desktop='^3' follow=on
bspc rule -a google-chrome-stable desktop='^3' follow=on
bspc rule -a Code desktop='^4' follow=on
bspc rule -a wpspdf desktop='^4' follow=on
bspc rule -a calibre desktop='^5' follow=on
bspc rule -a Steam desktop='^6' follow=on
bspc rule -a Clementine desktop='^7' follow=on
bspc rule -a SmartGit desktop='^8' follow=on
bspc rule -a thunar desktop='^8' follow=on
bspc rule -a telegram-desktop desktop='^9' follow=on
bspc rule -a zoom desktop='^9' follow=on
bspc rule -a Skype desktop='^9' follow=on
bspc rule -a Screenkey manage=off

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-1)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window